### ISSUE TITLE
Source Map request is forbidden using Lambda@Edge deployment

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#15]
**Describe the bug**
Having completed the last change related to enabling Rollbar on our SPA, we're now hitting a new problem when Rollbar attempts to download the source map for our bundle.

The server is returning a 403 response. 

**To Reproduce**
I've captured an example here:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/5343/60143032-c17a8e80-97ff-11e9-8a82-8afbd1887554.png">

Source Map Download Failed

Downloaded minified JS file at `https://app.digivizer.com/_assets/_public/static/js/2.1d1e308c.chunk.7e1f6c714.js`
HTTP 403 for referenced source map at `https://app.digivizer.com/_assets/_public/static/js/2.1d1e308c.chunk.js.map`

**Expected behavior**

This one, however, works:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/5343/60143103-fd155880-97ff-11e9-80ae-33b9c443bfdb.png">

Downloaded from `https://digivizer-a08887cfd-production.linc-preview.sh/static/js/2.f046640c.chunk.js.map` while processing an occurrence

**Comment by evanderkoogh** [comment]
Hey @qnm, I think I figured out what the problem is.

When your static assets are not in `/_assets` after building (like in the case of CRA, which puts them in `/static/`, `@fab/compile` will create redirects from `/stuff/*` to `/_assets/_public/stuff/*` and  also include a fingerprint in the URL. This works really well, except in this case, where someone is looking up something relative to the redirected URL.

@geelen I see a few different options:

* Figure out how to make CRA output their static assets in `/_assets` instead of `/static`. (Slightly better performance anyway
* Allow for a setting in `@fab/compile` to not fingerprint certain files/directories.

**Comment by evanderkoogh** [comment]
@qnm Can you give @geelen access to the repository again? He'll set it up a config that will output your static assets to `/_assets` so you won't have this problem.

Excuse us while we figure out the best to drive adoption of FABs forward. The end-goal is clear, but there is a lot of messy bits interacting with each other before we get to the point where framework output it natively and it is understood by hosting providers..

**Comment by qnm** [comment]
No problems @evanderkoogh , I've added @geelen to our repo again.

**Comment by geelen** [comment]
Hey Rob, apologies for the delay in replying. I've submitted a pull request
<https://github.com/digivizer/frontend/pull/581>with the necessary changes.
If you'd like to give that a look and get back to me if you think there are
any update needed?

Cheers,
-glen.
