### ISSUE TITLE
Unable to deploy using Cloudflare Workers

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#29]
**Describe the bug**
I've attempted to add Cloudflare Workers to our account (intending to work in addition to AWS - for now) but I see the follow error when doing so.

![image](https://user-images.githubusercontent.com/5343/81882949-57b1d180-95d7-11ea-943e-230c0694f17b.png)

**To Reproduce**
1. Add CF Workers deployment details
2. Save and Deploy
3. See failure

**Expected behavior**
I hoped to see the deploy take place

**Additional context**
We have existing CloudFront deployment which does not appear in the setup screen.

**Comment by evanderkoogh** [comment]
Hey @geelen, this looks like a FAB issue? We rolled out the new Cloudflare deployers on Linc right? Can you have a look?

**Comment by geelen** [comment]
Hey @qnm, the new Cloudflare Workers deployer only works with the newer versions of FABs, as does the new Lambda releaser. Your existing code is on the older Lambda releaser, which we've deprecated (we didn't mean to hide it from the settings screen, apologies about that).

If you can get a FAB v1 building on a branch as part of #26, we can pick a time to cut you over to the new releasers. We're working on the ability to deploy different branches to different places, so you could get the new FABs deploying & tested on Cloudflare (on a `next.` subdomain, say), then we can cut that over to your production domain.

**Comment by qnm** [comment]
@geelen There's a branch called 'fab' that contains the FABv1 migration.

**Comment by qnm** [comment]
@geelen This is now deployed however the site is not accessible using the `workers.dev` URL.

`522` error from Cloudflare.

Root

```
qnm@ryzen ~> curl -I https://app.digivizer.workers.dev/
HTTP/2 522 
date: Thu, 21 May 2020 23:21:59 GMT
content-type: text/html
set-cookie: __cfduid=da51f3543a1861430b4227189ad4b62561590103288; expires=Sat, 20-Jun-20 23:21:28 GMT; path=/; domain=.digivizer.workers.dev; HttpOnly; SameSite=Lax
cache-control: no-store, no-cache
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 597208b13fc9da4a-SYD
cf-request-id: 02db23c2c40000da4a2e802200000001
```


Static File

```
qnm@ryzen ~> curl -I https://app.digivizer.workers.dev/platform.jpg
HTTP/2 522 
date: Thu, 21 May 2020 23:21:07 GMT
content-type: text/html
set-cookie: __cfduid=d5253141110bcb97f9ba309677a66cc621590103252; expires=Sat, 20-Jun-20 23:20:52 GMT; path=/; domain=.digivizer.workers.dev; HttpOnly; SameSite=Lax
cache-control: no-store, no-cache
cf-cache-status: MISS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 597207ce0e69fd3a-SYD
cf-request-id: 02db2334c90000fd3a5c26f200000001
```

**Comment by plexey** [comment]
Hey @qnm, I think I may have fixed this.

I just had a quick look at your Cloudflare deployment config behind the scenes and noticed that no script name had been set. 

This was likely caused by an API bug which has since been patched. I've now set the script name and triggered a re-deployment.

Here's what I'm currently gettting when curling your worders.dev domain:
```
➜  ~ curl -I https://app.digivizer.workers.dev/
HTTP/2 200 
date: Fri, 22 May 2020 05:34:16 GMT
content-type: text/html
content-length: 4691
set-cookie: __cfduid=db2fff8f22010814af83a69314747c9ab1590125656; expires=Sun, 21-Jun-20 05:34:16 GMT; path=/; domain=.digivizer.workers.dev; HttpOnly; SameSite=Lax
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 59742ac92ba0fea1-MEL
cf-request-id: 02dc7911b70000fea1b9911200000001
```

**Comment by qnm** [comment]
@plexey Ah! Thanks. I will add the relevant CORS to make that work.

When I want to use this on a domain, what (DNS) steps do I need to take, if any?

**Comment by geelen** [comment]
All you need is a dummy DNS record for SSL, since every request is handled by the FAB running in the worker:

![image](https://user-images.githubusercontent.com/23264/82654816-31181a00-9c19-11ea-9271-8d5c94993ebe.png)

Linc will manage which domain to which FAB, though, so you only need to set up these DNS values once, and then they can just sit there (so you can start with `preview.digivizer.com` then flick across to `app.digivizer.com` just by changing the domain in Linc.

If anything goes wrong, the way Cloudflare wires up DNS to Workers is in your Cloudflare dashboard, looks like:

![image](https://user-images.githubusercontent.com/23264/82655779-a0dad480-9c1a-11ea-8ff2-bacc9cfc4eee.png)

Delete your `app.digivizer.com` line there if you want to let traffic flow through to AWS Lambda@Edge again. (obviously, this is assuming you have a real origin/CNAME for the `app.` subdomain, so don't change your existing value there)

**Comment by qnm** [comment]
I've been able to deploy using Workers, thanks for your help!
