### ISSUE TITLE
Locale differences in the Linc build environment

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#30]
**Describe the bug**
I'm seeing a test discrepancy between our own CI environment, which is Github Actions based, and that of Linc.

This appears to relate to locale - which I am sure is not being set explicitly inside the GH Actions CI environment.

![image](https://user-images.githubusercontent.com/5343/82172997-3b7f9e80-990f-11ea-81c7-980514298e2d.png)

It's entirely possible this related to my lack of understanding on Node. Any help appreciated!

The failing code looks a bit like:

```
const CURRENCY_FORMAT = { style: "currency", currency: "AUD" };
{value.toLocaleString("en-AU", CURRENCY_FORMAT)}
```

**To Reproduce**
1. All builds seem to be failing :(

**Expected behavior**
Behaviour to match GH Actions CI

**Screenshots**

**Comment by evanderkoogh** [comment]
Hey @qnm, I am very glad my first hunch was correct, otherwise this could have been an amazing rabbit hole. The difference isn't in Locales, but Node versions.

Basically Node changed their output somewhere between the last Node LTS version (`12.16.2`) and the currently stable version (`13.10.1`).

I ran the following snippet in Node `12.16.2` and `13.10.1` & latest Firefox
``` javascript
const CURRENCY_FORMAT = { style: "currency", currency: "AUD" };
const hundred = 100
hundred.toLocaleString("en-AU", CURRENCY_FORMAT)
```

Node 12.16.2 -> `A$100`
Node 13.10.1 -> `$100`
Firefox -> `$100`

The quickest way to solve this is probably to set the engines field in `package.json` to the LTS version. We respect that setting so you will run on Linc on node version: `12.16.2`

But that doesn't solve your problem that different browsers/Node versions will do this differently. So if you want a consistent `A$100`, you probably want to write your own custom formatter.

Or use `value.toLocaleString` in your assert as well, so that at least it doesn't fail if it the underlying implementation is different than what you expect.

Closing this as it isn't a Linc issue. Feel free to reach out by email if you want me to follow up on anything :)
