### ISSUE TITLE
Dependabot Branch Build Not Accessible

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#31]
**Describe the bug**
Dependabot has generated a branch which is not accessible via the branch name URL. The commit URL works as intended.

Here's an example of a branch with this property:

https://app.linc.sh/sites/digivizer/commits/dependabot%2Fnpm_and_yarn%2Fintersection-observer-0.10.0

The commit build:

https://digivizer--15e446267--production.linc-preview.sh/

The branch build:

https://digivizer--production--dependabotnpmandyarnintersection-observer-0100.branch.linc-preview.sh/

Other dependabot branches work, but not all. I’ve never seen this issue on a branch we’ve created. 

**To Reproduce**
1. Dependabot creates a branch - can't add much more than that, sorry!

**Expected behavior**
I expect that the branch build will return my site.

**Comment by plexey** [comment]
Hi @qnm,

Thanks for bringing this one to our attention. We'll look into it and try and get that fixed.

**Comment by plexey** [comment]
This issue should be fixed now @qnm 

If you look at the branch preview URL that you provided us, it contains the label:

`digivizer--production--dependabotnpmandyarnintersection-observer-0100`

This label has a combined length of 69 characters, and it turns out that 69 characters exceeds [the URL label limit of 63 characters](https://en.wikipedia.org/wiki/Domain_Name_System#Domain_name_space). 

As a result, our servers were never receiving a request from you whenever you tried to visit that particular branch preview URL. This issue would only affect you if your branch names are rather long, as may be the case with Dependabot branch names.

Our current solution to this is issue is to clip branch names in the URL to 28 characters to ensure that the label doesn't exceed 63 characters.

With this clipping, you now get this functioning URL:

[https://digivizer--production--dependabottion-observer-0100.branch.linc-preview.sh/](https://digivizer--production--dependabottion-observer-0100.branch.linc-preview.sh/)

All your branch previews on [Linc](https://app.linc.sh/sites/digivizer) should now be updated to the new format and should be working.

Thanks for bringing this to our attention, and please let us know if you run into any other issues.
