### ISSUE TITLE
Auto deploy from Prismic Headless CMS when a content writer publishes a new article AKA help me get webhooks working

### ISSUE THREAD

**Issue by evolve2k** [bitgenics/linc#40]
My project runs Prismic Headless CMS with Nuxt and deploys via Linc to Cloudflare Workers.

When I commit changes to my main branch, everything deploys correctly with Linc including pulling the latest dynamic data from my headless CMS (prismic) and rolling that into the static FAB bundle.

Now I want to support when my end user (content writers) make changes in the Prismic Writers Room and go to deploy new pages/posts where no other code has changed.

Prismic provides support for webhooks.
ref: https://user-guides.prismic.io/en/articles/790505-webhooks

How do I configure things so that published updates within primsic, initiate a rebuild and deploy from Linc?

**Comment by evolve2k** [comment]
Here's the UI on Prismic's end fwiw, the documentation url is the page included above.

![prismic_io_-_braveenergysystems](https://user-images.githubusercontent.com/114459/99035073-b54ac900-25ce-11eb-996e-fd7529615cca.png)

**Comment by geelen** [comment]
Hey Richie, we don't have a mechanism for content-driven rebuilds at the moment and might not for a little bit. What you'd need to do is trigger a git commit on your repository somehow, potentially there's a way to do that with Github actions?

Basically, Linc has a fairly fundamental assumption that a build should be idempotent, so building commit A always gives bundle B. But if you're accessing dynamic data like Prismic, that's no longer true, so our system doesn't have a natural way of doing this. So the best thing to do would be to create a commit dynamically when the content changes (it has to touch the repository btw, it can't be an empty commit, but a timestamp `latest_update` file would be fine), then Linc will work the way you expect, including rollbacks.

When we come back to bring native webhook Jamstack support we'll probably model things like this behind the scenes anyway, otherwise we'd weaken too many of the guarantees around the auto releasing. But as I said, we're not going to be able to ship that in the immediate future, so you'd be best to find a workaround. Sorry!

**Comment by evolve2k** [comment]
> Basically, Linc has a fairly fundamental assumption that a build should be idempotentHi @geelen that makes good sense.
That makes good sense generally.

Appreciate the guidance. 
> What you'd need to do is trigger a git commit on your repository somehow, potentially there's a way to do that with Github actions?

I'm going to work towards that exact approach of adding a timestamp to a log file using github actions.

Thanks for the guidance. All good.

When I work out how to do it, I'll come back here and update this issue for others who may be looking to do something similar.

_If anyone else is out there who's reading this and is right across using Github Actions for the above, shout out._ 😛

**Comment by evolve2k** [comment]
For anyone following along here rough intructions on implementing this.
Refs
[1] https://blog.s1h.org/github-actions-webhook/
[2] http://www.btellez.com/posts/triggering-github-actions-with-webhooks.html

### 1. Add .github/publish.yml to your repo.

Here's the code:

```
# .github/publish.yml

name: publish
on: [workflow_dispatch, repository_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date > published.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Published Changes"
          git push
```

### 2. Create Github Personal Access Token with Workflow Permissions

In github, click your face > Settings > Developer Settings and add a Personal Access Token
Use that as your Authorization Token.

### 3. Setup your webhooks to point to github

Reference Github in where you'd enter your webhook configuration.

URL STRUCTURE FOR THE WEBHOOK
https://api.github.com/repos/:owner/:repo/dispatches

AUTH TOKEN > Your Personal Access Token

**Comment by evolve2k** [comment]
Thanks for your help Glen 👍

**Comment by geelen** [comment]
Oh that's awesome! I think that's worth an entry on the docs!
