### ISSUE TITLE
Current Release has not updated nor deployed [digivizer]

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#8]
**Describe the bug**
After committing to the master branch (which was a squash commit), the Current Release has not updated nor been deployed.

**To Reproduce**
1. Accept a PR and commit to the master branch

**Expected behavior**
The master branch should be deployed. It was not.

**Additional context**

**Comment by evanderkoogh** [comment]
Hey @qnm. I am working on this right now. Will update when I have more info.

**Comment by evanderkoogh** [comment]
@qnm I have managed to track down the problem and it looks like there was a glitch in some of the DynamoDB triggers. I have manually fixed your data and that released your site.

I have a request outstanding with AWS to investigate the root cause of this and an internal issue to detect this and notify us when it happens.

Thanks!
